### ISSUE TITLE
V3 Testing

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Tanoa-Takedown#18]
ACE:
- Place Zeus Settings module
- Checked PLA rearm & repair, no sign of any syncing or variables to vehicle units.
- Check Advanced Medical settings. Currently medics have more privileges than doctors; who can only stitch.
- Sync medical facilities to module.
- Place Medical Settings module + configure

Gamemode module:
- the Zeus gamemode module is part of the framework for setting up the point-based system and resources etc. We've never used the module before. Currently it prevents you from accessing everything except markers in the create panel.

TFAR:
- TS channel not set

Player slots:
- AI being left in place after disconnects/switching slots
- Check Molokous inits; some spawn with ACRs/US kits

Loadouts:
- Still won't work because of subfolders. 'loadoutfolder' needs to contain the controller plus all the SQFs in one place. Alternatively, alter the init lines to loadoutfolder/TF Siren/script.sqf

Incognito:
- scripts are in but not configured. Would suggest making everyone blufor or IND to facilitate gameplay objectives

Weather:
- check ACE weather & attributes, continous fog at what looks to be 80%

15th PLA:
- May be related to the other PLA issue, inventory kit isn't spawning/being left behind on death, leaving players little to resupply/capture. No medical paraphernalia whatsoever.

**Comment by coachwn** [comment]
Not sure why ACE modules are messed up; also not sure why/how they were messed up to begin with since we had them . Went through them again last night before posting newest version on the server and setup the ACE medical again and triple checked against previous missions. 

Some of the Molo units are setup that way for testing. Better to have weapons for testing now; they are changing before final. 

On the loadouts I am confused here because Scotty's mission had them named "loadouts" and the loadout controller was in with all the sqf files like I had it originally.

TF Siren units are not going to be using Incognito. Only Independent will be using that IF it will work correctly.

**Comment by FoxKilo** [comment]
I'll fix/implement everything i've found so far in the above post, some of the main issues there (modules etc) may be down to corrupt PBO packing.

**Comment by coachwn** [comment]
Closing this so we can move ahead with V4
